<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThermoCore.Core\ThermoCore.Core.csproj" />
    <ProjectReference Include="..\ThermoCore.AWG\ThermoCore.AWG.csproj" />
    <ProjectReference Include="..\ThermoCore.Application\ThermoCore.Application.csproj" />
  </ItemGroup>

</Project>
