<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ThermoCore.Core\ThermoCore.Core.csproj" />
    <ProjectReference Include="..\ThermoCore.AWG\ThermoCore.AWG.csproj" />
    <ProjectReference Include="..\ThermoCore.App2.SolarAirHeater\ThermoCore.App2.SolarAirHeater.csproj" />
    <ProjectReference Include="..\ThermoCore.Persistence\ThermoCore.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
